#!/bin/bash
set -e

if [ $# -eq 0 ]
  then
    echo "The first argument needs to be the domain you got the LE certificate for. All the paths are generated using that domain"
fi

DOMAIN=$1

####################################################################################################
###### LEAVE THOSE ALONE ###########################################################################
# path of your certificat
CERTPATH=/etc/ssl/letsencrypt/$DOMAIN/$DOMAIN.cer
# path of your ca.cer, should be next to you certificate (downloaded by le automatically)
CAPATH_SOURCE=/etc/ssl/letsencrypt/$DOMAIN/ca.cer
# just leave that
CAPATH=/opt/zimbra/data/le_ca.cer
# that is something you need to download yourself from
ROOTPATH=/etc/ssl/le_root.cer
KEYPATH=/etc/ssl/letsencrypt/$DOMAIN/$DOMAIN.key

echo "adding root.cer ca.cer to the end of the certificate due to the keytool greatness... we have to add the root "
sudo -u zimbra cp $CAPATH_SOURCE $CAPATH
# concat CA to the end of CERT
sudo -u zimbra cat $ROOTPATH >> $CAPATH

echo "verify cert"
sudo -u zimbra /opt/zimbra/bin/zmcertmgr verifycrt comm $KEYPATH $CERTPATH $CAPATH

echo "copying private key to /opt/zimbra/ssl/zimbra/commercial/commercial.key"
sudo -u zimbra cp $KEYPATH /opt/zimbra/ssl/zimbra/commercial/commercial.key

echo "installing certificate"
sudo -u zimbra /opt/zimbra/bin/zmcertmgr deploycrt comm $CERTPATH $CAPATH
sudo -u zimbra /opt/zimbra/bin/zmcontrol restart
